# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod Properties
mod_id = wbreminders
mod_name = Wellbeing Reminders
mod_version = 1.0.1
mod_description = A mod that reminds you to take care of irl self while playing! (Reminders to hydrate, stretch, do wrist excersises, take breaks and sleep)
mod_license = MIT
mod_authors = JustMili

maven_group = net.justmili.reminders
archives_base_name = WellbeingReminders

minecraft_version_constraint_fabric = 26.2
supported_versions = 26.2

# Dependencies
mod_menu = 20.0.0-beta.4
sodium = 0.9.1-beta.2